- type: job
  id: TownSheriff
  setPreference: true
  name: job-name-townsheriff
  description: job-description-townsheriff
  playTimeTracker: TownSheriff
  requirements:
    - !type:CharacterDepartmentTimeRequirement
      department: Townsfolk
      min: 18000 # 5 hours
  startingGear: TownSheriffGear
  icon: "JobIconPassenger"
  supervisors: job-supervisors-townsfolk
  access:
  - TownieLaw
<<<<<<< HEAD
  - TownieMechanic
=======
>>>>>>> private/UpOctober
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - Townsfolk

<<<<<<< HEAD
- type: startingGear
  id: TownSheriffGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitCowboyGrey
    back: N14ClothingBackpackSheriffFilled
    shoes: N14ClothingBootsCowboy
    head: N14ClothingHeadHatSheriff
    eyes: N14ClothingEyesSunGlasses
    id: N14IDBadgeTownSheriff
    outerClothing: N14ClothingOuterSheriffVest
    belt: ClothingBeltRevolverWildWhisper
    pocket1: RadioHandheld
    pocket2: Handcuffs
  satchel: N14ClothingBackpackSatchelSheriffFilled
  duffelbag: N14ClothingBackpackDuffelSheriffFilled

=======
>>>>>>> private/UpOctober
- type: playTimeTracker
  id: TownSheriff
