- type: job
  id: TownDeputy
  setPreference: true
  name: job-name-towndeputy
  description: job-description-towndeputy
  playTimeTracker: TownDeputy
  requirements:
    - !type:CharacterDepartmentTimeRequirement
      department: Townsfolk
      min: 3600 # 1 hours
  startingGear: TownDeputyGear
  icon: "JobIconPassenger"
  supervisors: job-supervisors-townsfolk
  access:
  - TownieLaw
<<<<<<< HEAD
  - TownieMechanic
=======
>>>>>>> private/UpOctober
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - Townsfolk

<<<<<<< HEAD
- type: startingGear
  id: TownDeputyGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitCowboyBrown
    head: N14ClothingHeadHatDeputy
    eyes: N14ClothingEyesSunGlasses
    back: N14ClothingBackpackDeputyFilled
    shoes: N14ClothingShoesBlack
    id: N14IDBadgeTownDeputy
    outerClothing: N14ClothingOuterPoliceVest
    belt: ClothingBeltRevolverfilled
    pocket1: RadioHandheld
    pocket2: Handcuffs
  satchel: N14ClothingBackpackSatchelDeputyFilled
  duffelbag: N14ClothingBackpackDuffelDeputyFilled

=======
>>>>>>> private/UpOctober
- type: playTimeTracker
  id: TownDeputy
