- type: job
  id: BoSWashingtonRecruit
  setPreference: true
  name: job-name-bos-washington-recruit
  description: job-description-bos-washington-recruit
  playTimeTracker: BoSWashingtonRecruit
  requirements: # Corvax-MRP
    - !type:OverallPlaytimeRequirement
      time: 7200 # 2 hour
  startingGear: BoSWashingtonRecruitGear
  alwaysUseSpawner: true
  icon: "JobIconPassenger"
  supervisors: job-supervisors-bos-washington-recruit
  canBeAntag: false
  access:
  - WashingtonInitiate
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - BrotherhoodWashington
  jobBlockForSpecies:
  - !type:JobBlockForSpecie
    nameSpecie: Ghoul
  - !type:JobBlockForSpecie
    nameSpecie: GhoulGlowing

- type: startingGear
  id: BoSWashingtonRecruitGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitBOSRed
    back: N14ClothingBackpackMilitary
    shoes: N14ClothingBootsCombatFilled
    head: N14ClothingHeadHatBrotherhoodHelmet # Crovax-N14
    id: N14IDWashingtonBrotherhoodHolotagRecruit # Crovax-N14
    outerClothing: N14ClothingOuterCombatArmorBOS
    belt: ClothingBeltBoSWebbing
    pocket1: BoSWashingtonStandartKits # Crovax-N14

- type: playTimeTracker
  id: BoSWashingtonRecruit
