- type: job
  id: BoSWashingtonResearcher
  setPreference: true
  name: job-name-bos-washington-researcher
  description: job-description-bos-washington-researcher
  playTimeTracker: BoSWashingtonResearcher
  startingGear: BoSWashingtonResearcherGear
  icon: "JobIconScientist"
  supervisors: job-name-bos-washington
  access:
  - WashingtonInitiate
  - WashingtonScribe

- type: startingGear
  id: BoSWashingtonResearcherGear
  equipment:
    head: N14ClothingHeadHatBrotherhoodBeret
    jumpsuit: N14ClothingUniformJumpsuitBOSBlack
    satchel: N14ClothingBackpackSatchelMilitary
    shoes: N14ClothingBootsCombat
    outerClothing: N14ClothingOuterBosScribe
    id: N14IDBrotherhoodHolotag
    ears: ClothingHeadsetScience #placeholder
    belt: N14ClothingBeltUtilityFilled

- type: playTimeTracker
  id: BoSWashingtonResearcher
